name: Staking CI

on:
  push:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v2

      # This was yarn v1 only and yarn v3 fails to run
      - run: unset YARN_PRODUCTION

      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - run: yarn npm audit --recursive --severity critical
      - run: yarn install --immutable
      - run: yarn lint:sarif
      - run: yarn pretty:check
      - run: yarn test:unit

      - name: Upload lint results
        uses: github/codeql-action/upload-sarif@7fee4ca032ac341c12486c4c06822c5221c76533 # pin@codeql-bundle-20210517
        with:
          sarif_file: lint-results.sarif
        continue-on-error: true

      - name: Cache next.js build cache
        uses: actions/cache@a7c34adf76222e77931dedbf4a45b2e4648ced19
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-next-cache-${{ hashFiles('yarn.lock') }}
        continue-on-error: true

      - run: yarn build
      - run: tar -zcvf build.tar.gz .next

      - name: Archive build
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: build
          path: build.tar.gz
