name: Update dependency

on: workflow_dispatch

jobs:
  update_version:
    name: Update contracts-interface version
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-node/alpine:14.17
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v2

      - name: Set yarn cache directory
        run: yarn config set cache-folder .yarn-cache
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d # pin@v2
        with:
          path: |
            .yarn-cache
            node_modules
          key: ${{ runner.os }}-alpine-node-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-node-
        continue-on-error: true

      # fix: permission issues on ghactions+docker+npm@7
      - name: Chown workspace
        run: chown -R $(whoami) .

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Update all @synthetixio dependencies
        run: 'yarn run upgrade-synthetix'

      - name: Commit changes
        run: |
          export CONTRACT_VERSION="$(jq -r '.dependencies."@synthetixio/contracts-interface"' < package.json)"
          git config --global user.email "team@synthetix.io" && git config --global user.name "Synthetix Team"
          git commit -am "contracts-interface@$CONTRACT_VERSION"
          git push origin dev
