name: Update dependency

on:
  workflow_dispatch:
    inputs:
      monorepo_version:
        description: 'New Monorepo Version (ex. 2.50.0-alpha) (leave empty to "patch")'
        required: false

jobs:
  update_version:
    name: Update contracts-interface version
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-node/alpine:14.17
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v2

      - name: Set yarn cache directory
        run: yarn config set cache-folder .yarn-cache
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09 # pin@v2
        with:
          path: |
            .yarn-cache
            node_modules
          key: ${{ runner.os }}-alpine-node-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-node-
        continue-on-error: true

      # fix: permission issues on ghactions+docker+npm@7
      - name: Chown workspace
        run: chown -R $(whoami) .

      - name: Install dependencies
        run: yarn

      - name: Update all @synthetixio/* dependency
        run: "sed -i 's/\"@synthetixio\\/\\(.*\\)\": \".*\"/\"@synthetixio\\/\\1\": \"${{ github.event.inputs.monorepo_version }}\"/' package.json"

      - run: yarn

      - name: Commit changes
        run: |
          git config --global user.email "team@synthetix.io" && git config --global user.name "Synthetix Team"
          git commit -am 'contracts-interface@${{ github.event.inputs.version }}'
          git push origin dev
